name: Push monocle to pypi

on:
  workflow_dispatch:
    inputs:
      PYPI_REPO: 
        default: 'testpypi'
        type: string

jobs :
  push-monocle-pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Make the script files executable
        run: chmod +x ./scripts/push-pypi.sh
      - name: Run a script
        env:
          PYPI_USERNAME: __token__
          PYPI_PASSWORD: ${{ inputs.PYPI_REPO == 'pypi' && secrets.PYPI_TOKEN || secrets.TEST_PYPI_TOKEN }}
          PYPI_REPO: ${{ inputs.PYPI_REPO }}
        run: ./push-pypi.sh

          
