name: Push monocle to pypi

on:
  workflow_dispatch:
    inputs:
      PYPI_REPO: 
        default: 'testpypi'
        type: string

jobs :
  push-monocle-pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Make the script files executable
        run: chmod +x ./scripts/push-pypi.sh
      - name: Run a script
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          PYPI_REPO: ${{ inputs.PYPI_REPO || 'testpypi'}}
        run: ./push-pypi.sh

          
