name: Send Email
on: push
jobs:
  send_email:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello World
      run: echo "This is a placeholder step to demonstrate email sending."

    - name: Send Email Notification
      if: always()
      uses: dawidd6/action-send-mail@v6
      with:
        server_address: smtp.gmail.com
        server_port: 587
        secure: false
        username: ${{ secrets.GMAIL_USERNAME }}
        password: ${{ secrets.GMAIL_APP_PASSWORD }}
        subject: Github Actions job result
        to: ashokan.perumal@okahu.ai
        from: ${{ secrets.GMAIL_USERNAME }}
        body: This is a test email sent from a GitHub Action workflow.
  
        