

name: Tox

on:
  push:
    branches: [ "main", "kshitiz/update_test" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
  tox:
    name: Run tox
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tox
        run: |
          python -m pip install --user tox

      - name: Run tox tests
        run: python -m tox -c tox.ini